linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck

run:
  # default concurrency is a available CPU number.
  # concurrency: 2 # explicitly omit this value to fully utilize available resources.
  timeout: 2m
  modules-download-mode: readonly
  issues-exit-code: 0
  tests: false